[build]
  base = "packages/app"
  publish = "dist"
  command = "npm run build"
[[redirects]]
  from = "/*.json"
  to = "/:splat"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
