version: "3.7"
services:
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - "couchdb"
    environment:
      DB_HOST: http://couchdb:5984
    networks: 
      - backend
  couchdb:
    image: couchdb
    ports:
      - "5984:5984"
    volumes:
      - couchdb:/opt/couchdb/data
    networks: 
      - backend
volumes:
  couchdb:
networks:
  backend:
    driver: "bridge"