version: "3.7"
services:
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - "db"
  db:
    image: couchdb
    ports:
      - "5984:5984"
    volumes:
      - couchdb:/couchdb
volumes:
  couchdb:
  pouchdb: